name: Insurance Business Services Build

on:
  push:
    branches:
      - development  # Trigger on push to the development branch

jobs:
  setup:
    runs-on: ubuntu-latest  # Use Ubuntu or Windows, depending on your preference

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Specify Node.js version

      - name: Create folder and navigate into it
        run: |
          mkdir -p Insurance-Business-Services
          cd Insurance-Business-Services

      - name: Git Pull - lipas-client
        run: |
          cd Insurance-Business-Services
          git clone --branch development https://github.com/VAINS-Dev/LIPAS-Client.git
          cd LIPAS-Client
          npm install

      - name: Git Pull - archer
        run: |
          cd Insurance-Business-Services
          git clone --branch development https://github.com/VAINS-Dev/A.R.C.H.E.R.git
          cd A.R.C.H.E.R
          npm install

      - name: Log successful completion
        run: echo "Repositories successfully cloned and dependencies installed."