name: CI Pipeline with MSSQL Server

on:
  push:
    branches:
      - main

jobs:
  mssql:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Wait for SQL Server to Be Ready
      run: |
        for i in {1..10}; do
          if /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -Q "SELECT 1" > /dev/null 2>&1; then
            echo "SQL Server is ready!"
            break
          fi
          echo "Waiting for SQL Server..."
          sleep 5
        done

    - name: Install SQLCMD Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Execute SQL Scripts from Folder
      run: |
        for file in ./.GitHub-CI/Database/*.sql; do
          echo "Executing $file..."
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -i $file
        done

    - name: Pull Down Repository Copy
      run: |
        git clone https://github.com/${{ github.repository }} cloned-repo
        ls cloned-repo
