name: Build CI-CD

on:
  push:
    branches:
      - main

jobs:
  mssql:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Wait for SQL Server to Be Ready
      run: |
        for i in {1..10}; do
          if /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -Q "SELECT 1" > /dev/null 2>&1; then
            echo "SQL Server is ready!"
            break
          fi
          echo "Waiting for SQL Server..."
          sleep 5
        done
    
        # Fail the step if the server is still not available
        if ! /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -Q "SELECT 1"; then
          echo "SQL Server is not ready after waiting."
          exit 1
        fi

    - name: Install SQLCMD Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Execute SQL Scripts from Folder
      run: |
        for file in ./.GitHub-CI/Database/*.sql; do
          echo "Executing $file..."
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -i $file
        done

    # Step 5: Install Mockoon CLI
    - name: Install Mockoon CLI
      run: |
        npm install -g @mockoon/cli
    # Step 6: Start Mockoon Server Instances
    - name: Start Mockoon Servers
      run: |
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/V20.SP4/EXL_LifePRO_LPRestClaimAPI.json --port 3000 > ./mockoon-3000.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/V20.SP4/EXL_LifePRO_LPRestPartyAPI.json --port 3001 > ./mockoon-3001.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/V20.SP4/EXL_LifePRO_LPRestPolicyAPI.json --port 3002 > ./mockoon-3002.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/V20.SP4/EXL_LifePRO_LPRestProductAPI.json --port 3003 > ./mockoon-3003.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/V20.SP4/EXL_LifePRO_UserMgmtService.json --port 3004 > ./mockoon-3004.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/LDS/LDS_Workflow_CommonService.json --port 3005 > ./mockoon-3005.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/LDS/LDS_Workflow_UnderWritingService.json --port 3006 > ./mockoon-3006.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/LDS/LDS_Workflow_WorkflowService.json --port 3007 > ./mockoon-3007.log 2>&1 &
        nohup mockoon-cli start --data ./.GitHub-CI/Mockoon/InsuranceServices/InsuranceServices.json --port 3008 > ./mockoon-3008.log 2>&1 &



    - name: Wait for Mockoon Servers to Start
      run: |
        for port in 3000 3001 3002 3003 3004 3005 3006 3007 3008; do
          for i in {1..10}; do
            if curl --silent http://localhost:$port; then
              echo "Mockoon server on port $port is ready"
              break
            fi
            echo "Waiting for Mockoon server on port $port..."
            sleep 3
          done
        done


    - name: Check Mockoon Logs
      run: |
        tail ./mockoon-*.log


    # Step 7: Verify Mockoon Server is Running
    - name: Validate Mockoon Endpoints
      run: |
        # LPRestClaim
        curl -s -X GET -o /dev/null -w "%{http_code}" http://localhost:3000/LPRestClaim \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3000 failed"

        # LPRestParty
        curl -s -X GET -o /dev/null -w "%{http_code}" http://localhost:3001/LPRestParty \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3001 failed"

        # LPRestPolicy
        curl -s -X GET -o /dev/null -w "%{http_code}" http://localhost:3002/LPRestPolicy \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3002 failed"

        # LPRestProduct
        curl -s -X GET -o /dev/null -w "%{http_code}" http://localhost:3003/LPRestProduct \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3003 failed"

        # Authz Token
        curl -s -X GET -o /dev/null -w "%{http_code}" http://localhost:3004/authz/token \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3004 failed"

        # CommonService
        curl -s -X POST -o /dev/null -w "%{http_code}" http://localhost:3005/ulissia-webservices/services/CommonService?wsdl \
          -H "Content-Type: text/xml" \
          -d '<?xml version="1.0" encoding="UTF-8"?>
              <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                <soapenv:Header/>
                <soapenv:Body>
                  <ns1:Request xmlns:ns1="http://example.com/commonservice">
                    <ns1:Parameter>Value</ns1:Parameter>
                  </ns1:Request>
                </soapenv:Body>
              </soapenv:Envelope>' || echo "Port 3005 failed"

        # UnderwritingService
        curl -s -X POST -o /dev/null -w "%{http_code}" http://localhost:3006/ulissia-webservices/services/UnderwritingService?wsdl \
          -H "Content-Type: text/xml" \
          -d '<?xml version="1.0" encoding="UTF-8"?>
              <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                <soapenv:Header/>
                <soapenv:Body>
                  <ns1:Request xmlns:ns1="http://example.com/underwritingservice">
                    <ns1:Parameter>Value</ns1:Parameter>
                  </ns1:Request>
                </soapenv:Body>
              </soapenv:Envelope>' || echo "Port 3006 failed"

        # WorkflowService
        curl -s -X POST -o /dev/null -w "%{http_code}" http://localhost:3007/ulissia-webservices/services/WorkflowService?wsdl \
          -H "Content-Type: text/xml" \
          -d '<?xml version="1.0" encoding="UTF-8"?>
              <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                <soapenv:Header/>
                <soapenv:Body>
                  <ns1:Request xmlns:ns1="http://example.com/workflowservice">
                    <ns1:Parameter>Value</ns1:Parameter>
                  </ns1:Request>
                </soapenv:Body>
              </soapenv:Envelope>' || echo "Port 3007 failed"

        # InsuranceServices
        curl -s -X POST -o /dev/null -w "%{http_code}" http://localhost:3008/InsuranceServices \
          -H "Content-Type: application/json" -d '{}' || echo "Port 3008 failed"





